### ISSUE TITLE
Multi Labels

### ISSUE THREAD

**Issue by sassyn** [dodopizza/prometheus-shell-exporter#5]
Hi,

Great Tool thank you!

I have a bash script which create two labels, something like:

function gauge_vector(){
    jq -n \
        --arg value "${1}" \
        --arg stream_id "${2}" \
        '{
            "value": $value | tonumber,
            "labels": {
               "labelX": foo,
               "labelY": bar
            }
        }'
}

When running the binary I get:
go run exporter.go

{"level":"debug","time":"2021-07-17T19:29:45Z","message":"start exporter"}
panic: inconsistent label cardinality: expected 1 label values but got 2 in prometheus.Labels{"labelY":"bar", "labelX":"foo"}

goroutine 22 [running]:
github.com/prometheus/client_golang/prometheus.(*GaugeVec).With(0xc0000a22b8, 0xc00015c6f0, 0xc0000a11b0, 0xe)
        /root/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/gauge.go:228 +0xc2
github.com/dodopizza/prometheus-shell-exporter/internal/shell-exporter/go.(*Collector).Collect(0xc00008bf80, 0xc000078240)
        /tmp/9/prometheus-shell-exporter/internal/shell-exporter/go/collector.go:84 +0x2b0
github.com/prometheus/client_golang/prometheus.DescribeByCollect.func1(0xa5fee0, 0xc00008bf80, 0xc000078240)
        /root/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/collector.go:90 +0x3b
created by github.com/prometheus/client_golang/prometheus.DescribeByCollect
        /root/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/collector.go:89 +0x75
exit status 2

Is it possible to fix this?
Thank you

**Comment by vitalyu** [comment]
Hi, @sassyn 
Thanks for your feedback. We will reproduce the issue and fix it this week

**Comment by vitalyu** [comment]
Hi, @sassyn
Thanks for your feedback. I have successfully reproduced your issue.

So. The error's reason is in same labels values You tried to pass to loop

Example:
```
function gauge_vector(){
    jq -n \
        --arg value "${1}" \
        --arg label1 "${2}" \
        '{
            "value": $value | tonumber,
            "labels": {
                "labelX": "foo",
                "labelY": "bar"
            }
        }'
}

...

for i in $(seq 1 10)
do
    add_gauge_vector ${RANDOM} "for_${i}"
done

```
This example got the error, because you tried to create 10 metrics with the same labels pairs.

Workable example:
```
function gauge_vector(){
    jq -n \
        --arg value "${1}" \
        --arg label1 "${2}" \
        '{
            "value": $value | tonumber,
            "labels": {
                "example": $label1,
                "labelX": "foo",
                "labelY": "bar"
            }
        }'
}
```
returns
```
# HELP bash_gauge 
# TYPE bash_gauge gauge
bash_gauge{example="for_1",labelX="foo",labelY="bar"} 29533
bash_gauge{example="for_10",labelX="foo",labelY="bar"} 294
bash_gauge{example="for_2",labelX="foo",labelY="bar"} 18531
bash_gauge{example="for_3",labelX="foo",labelY="bar"} 31330
bash_gauge{example="for_4",labelX="foo",labelY="bar"} 18430
bash_gauge{example="for_5",labelX="foo",labelY="bar"} 24728
bash_gauge{example="for_6",labelX="foo",labelY="bar"} 11015
bash_gauge{example="for_7",labelX="foo",labelY="bar"} 15140
bash_gauge{example="for_8",labelX="foo",labelY="bar"} 2534
bash_gauge{example="for_9",labelX="foo",labelY="bar"} 18432
```

Also, if you want to discover the exporter's code, I suggest You to try [VSCode Remote containers](https://code.visualstudio.com/docs/remote/containers) instead of local setup. This repo has predefined development environment (.devcontainer)
